export const INCREMENT_APP_COUNT = 'INCREMENT_APP_COUNT';
export const DECREMENT_APP_COUNT = 'DECREMENT_APP_COUNT';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';